name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pyproject-${{ hashFiles('**/pyproject.toml') }}
      - name: Setup
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry install --only docs
      - run: poetry run mkdocs gh-deploy --force
