on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/european-xfel/pyvarium:test
      credentials:
        username:  ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ matrix.python-version }}-pip-${{ hashFiles('**/pyproject.toml') }}
      - name: Setup
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"
      - name: Test
        run: |
          python3 -m pytest -n auto --dist loadfile
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
